### ISSUE TITLE
Why is functionality so limited?

### ISSUE THREAD

**Issue by barseghyanartur** [trieb-work/linkedin-voyager-sdk#3]
Voyager API supports so much more.

**Comment by JannikZed** [comment]
hey @barseghyanartur you are right! I just started out - so that's why I just added these functions... as there is no official documentation it is not that easy to implement new functionalities :D 
do you want to contribute?

**Comment by barseghyanartur** [comment]
@JannikZed:

But [there is](https://linkedin.api-docs.io/v1.0/search/RWHmniwaq7msAoZTM). 

At the moment I'm using [this Python package](https://github.com/tomquirk/linkedin-api) for it, which does the job nicely, but I would rather use Node.

I don't think I would have time for implementing this myself. Sorry.
